version: '3'

volumes:
  backend_vol:
  frontend_vol:

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/home/app
      - backend_vol:/home/app/node_modules
    environment:
      - PORT=3000
      - ORIGIN=http://localhost:3002
    ports:
      - 3000:3000
    depends_on:
      - frontend
    container_name: backend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/home/app
      - frontend_vol:/home/app/node_modules
    environment:
      - REACT_APP_PORT=3000
      - REACT_APP_BACKEND=http://localhost:3000
    ports:
      - 3002:3000
    container_name: frontend
