POST http://localhost:3000/api/notes HTTP/1.1
content-type: application/json

{
    "number": "111-222333"
}

###
GET http://localhost:3000/api/notes/mustafa HTTP/1.1
content-type: application/json

###
DELETE http://localhost:3000/api/notes/mustafa
