version: '3'

services:
  website:
    build:
      context: ./website/
    ports: 
      - '127.0.0.1:3001:3000'
    volumes:
      - ./website:/root/app/
    container_name: website
  
  server:
    image: clue/json-server
    ports: 
    - '127.0.0.1:3002:80'
    volumes:
      - ./server/data.json:/data/db.json
    container_name: server
