version: '3'

services:
  frontend:
    build:
      context: ./website/
    ports: 
      - 3000
    volumes:
      - ./website:/root/app/
    environment:
      - VIRTUAL_HOTS=frontend.colasloth.com
    container_name: frontend
  
  backend:
    image: clue/json-server
    ports: 
      - 80
    volumes:
      - ./server/data.json:/data/db.json
    environment:
      - VIRTUAL_HOTS=backend.colasloth.com
    container_name: backend

  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    environment:
      - VIRTUAL_HOTS=nginx.colasloth.com
    depends_on:
      - frontend
      - backend
    container_name: nginx
