version: '3'

services:
  frontend:
    build:
      context: ./website/
    ports: 
      - '127.0.0.1:3000:3000'
    volumes:
      - ./website:/root/app/
    container_name: frontend
  
  backend:
    image: clue/json-server
    ports: 
      - '127.0.0.1:3002:80'
    volumes:
      - ./server/data.json:/data/db.json
    container_name: backend

    #  nginx:
    #    image: jwilder/nginx-proxy
    #    volumes:
    #      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #      - /var/run/docker.sock:/tmp/docker.sock:ro
    #    ports:
    #      - 80:80
    #    environment:
    #      - VIRTUAL_HOTS=nginx.colasloth.com
    #    depends_on:
    #      - frontend
    #      - backend
    #    container_name: nginx
    
        #    environment:
        #      - VIRTUAL_HOST=backend.colasloth.com

        #    environment:
        #      - VIRTUAL_HOST=frontend.colasloth.com
