version: '3'

volumes:
  node_modules:

services:
  frontend:
    build:
      context: ./frontend/
    ports:
      - 3000
    volumes:
      - ./frontend:/root/app/
      - node_modules:/root/app/node_modules
    environment:
      - VIRTUAL_HOSTS=frontend.colasloth.com
    container_name: frontend

  backend:
    image: clue/json-server
    ports:
      - 80
    volumes:
      - ./backend/data.json:/data/db.json
    environment:
      - VIRTUAL_HOSTS=backend.colasloth.com
    container_name: backend

  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    environment:
      - VIRTUAL_HOSTS=phonebook.colasloth.com
    depends_on:
      - frontend
      - backend
    container_name: nginx
